defaults:
  - env: mila # dev: local.yaml, testbed: mila.yaml
  - experiment: eicu
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
hydra:
  run:
    dir: .
  output_subdir: null
